src/com/koxudaxi/pydantic/PydanticInspection.kt

When Calling object, The plugin may detect an object as other class.
Also, if the class is multiple inheritances, then the plugin doesn't show a warning message.
The PR fixes it.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/17

fix to handle class

---

src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

The PR supports `ellipsis(...)` on the 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/30

support ellipsis

---

README.md
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt

The PR supports a few features in refactoring fields function
- refactor fields by keyword arguments on `__init__`
- refactor  super-classes include keywords arguments  of `__init__`
- refactor inheritor-classes include keywords arguments  of `__init__`
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/29

support refactoring fields by a keyword argument

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

The PR removes  warning of arguments is requierd because `BaseSettings` can parse environment variables in `__init__`
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/32

Support BaseSettings

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

The PR fixes to check the type of field without a type-hint 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/37

 fix no annotated fields

---

README.md
build.gradle
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticBaseModel.kt
src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt
src/com/koxudaxi/pydantic/PydanticFieldSearchExecutor.kt

The PR supports to search related fields from class attributes and keywords arguments of `__init__`.
It means The plugin can jump between fields and keyword arguments of `__init__` with `ctrl+b`
I feel very very useful feature.
btw,  PyCharm does not support the futures for dataclass of python
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/40

Support to search related fields

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

The PR support default values. the plugin show default values of `__init__` on a tooltip
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/44

Support default values

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
testData/completion/keywordArgument.py
testData/completion/keywordArgumentAssignValue.py
testData/completion/keywordArgumentInserted.py
testData/completion/keywordArgumentParent.py
testData/completion/keywordArgumentPythonClass.py
testData/completion/keywordArgumentPythonFunction.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR appends two features to improve autocompletion for signatures subclasses of pydantic.BaseModel and pydantic.dataclasses.dataclass.
- Priority showing the fields
If you enter `Ctr + Space`  or `Cmd + Space` on model Callers then,  Fields are shown on top.
eg: `Model(<here>)`
- Display definition Class
The information appears right side on the autocompletion list.

Improve autocompletion for signature

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt
src/com/koxudaxi/pydantic/PydanticFieldSearchExecutor.kt
testData/completion/instance.py
testData/completion/instanceBroken.py
testData/completion/instanceParent.py
testData/completion/instanceParentIsPythonClass.py
testData/completion/instancePythonClass.py
testData/completion/instancePythonFunction.py
testData/completion/instanceUnResolve.py
testData/completion/keywordArgumentAssignValue.py
testData/completion/keywordArgumentInserted.py
testData/completion/keywordArgumentParent.py
testData/completion/keywordArgumentPythonFunction.py
testData/completion/string.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR adds  a type and a default value on popup of auto-completion
#53

Add type and default value to popup of auto-completion

---

src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/assignedInstance.py
testData/completion/assignedInstancePythonClass.py
testData/completion/class.py
testData/completion/field.py
testData/completion/fieldOptional.py
testData/completion/fieldSchema.py
testData/completion/fieldUnion.py
testData/completion/instance.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR supports to show parsed types for fields completion.
The is a small feature. And the PR cover few cases. 
eg: 
```
class A(BaseModel):
item = Schema('apple')
a = A(item='orange')
a.item # auto-completion show type as str

Use parsed type for completion

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
testData/completion/pythonClass.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR fixes removing python class fields on auto-completion.
The plugin removes fields on auto-completion when reference subclass of pydantic.BaseModel and pydantic.dataclasses.dataclass.
However, a bug works on any class.
It means we can't see class attributes of any class on auto-completion.

Fix removing python class fields on auto-completion

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

This PR fixes wrong warning message for `cls` initialization.
I have added code to check whether the type of `cls` is pydantic model 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/65

fix wrong warning message for cls initialization

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt
src/com/koxudaxi/pydantic/PydanticFieldSearchExecutor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/assignedClass.py
testData/completion/classFields.py
testData/completion/parameterAnnotationType.py
testData/completion/parameterAnnotationTypeKeywordArgument.py
testData/completion/subscriptionClass.py
testData/mock/stub/typing/__init__.py
testData/search/keywordArgumentInFunctionByField.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticSearchTest.kt

The PR supports all features(type inspection, searching, refactoring...) by parameters which are in a function or methods.

support features by parameters

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler.kt

The PR improves to insert validate methods. 
PyCharm inserts method template when you type `def name(` in a class definition.
the method template has `self` or `cls` signature. PyCharm detects method type like `classmethod` and `staticmethod`.
PyCharm inserts `self` on validator methods.
Unfortunately, pydantic's validator method is classmethod.
The reason is validator methods don't have `@classmethod` decorator.
Also, The PR add inset the text `, `.  because validators need any argument.

Improve to insert validate methods

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt

The PR fixes a bug which fails autocompletion
The PR uses a safe cast for elements. aka `as?`
```
java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to class com.jetbrains.python.psi.PyTypedElement (com.intellij.psi.impl.source.tree.LeafPsiElement and com.jetbrains.python.psi.PyTypedElement are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @5700d6b1)
at com.koxudaxi.pydantic.PydanticCompletionContributor$FieldCompletionProvider.addCompletions(PydanticCompletionContributor.kt:161)
at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
at …
```

fix auto completion for Fields

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/classValidatorCls.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PRs fixes first parameter type of a validator method.
The type of parameter should be `Class`.
eg:
```
class Model(BaseModel):
bar: int
@validator('bar')
def fa(cls, bar):
cls  # <- cls is Class
```

Fix fisrt parameter type of a validator method

---

pydantic-pycharm-plugin.iml
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/fieldIgnore.py
testData/completion/keywordArgumentIgnore.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR ignore protected and private fields 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/77

ignore protected fields

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
testData/completion/config.py
testData/completion/configDefined.py
testData/completion/definedNestedClass.py
testData/completion/nestedClass.py
testData/mock/pydanticv1/__init__.py
testData/mock/pydanticv1/main.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR adds auto-completion for config fields.
The files come from `pydantic.BaseConfig`
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/83

Add auto-completion for config fields

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/inspection/ormMode.py
testData/mock/pydanticv1/main.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt

The PR supports to inspect `from_orm`.
If `orm_mode` is `False` and `from_orm` is called then, the plugin shows an error message.

Inspect from_orm

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/readOnlyProperty.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt

The PR supports to inspect the read-only property when  `allow_mutation` option is `False` on `Config`

Support to inspect read-only property

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

The PR fixes to reference valid local variables on a method. 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/89

Fix field names treated with incorrect scope

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/acceptsOnlyKeywordArguments.py
testData/inspection/acceptsOnlyKeywordArgumentsSingleStarArgument.py

The PR support positional arguments for dataclasses.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/88

Support positional arguments for dataclasses

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/PydanticInspection.html
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/inspection/warnUntypedFields.py
testData/inspection/warnUntypedFieldsDisable.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt

The PR supports to inspect untyped fields. The warning is related to mypy plugin's option on pydantic.
Also, This inspection is an option. Users can toggle the option by settings.

inspect untyped fields

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticConfigPanel.form
src/com/koxudaxi/pydantic/PydanticConfigPanel.java
src/com/koxudaxi/pydantic/PydanticConfigService.kt
src/com/koxudaxi/pydantic/PydanticConfigurable.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

The PR adds a config panel and saves configurations on an XML file.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/36
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/78
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/87

add config panel

---

src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/warnUntypedFields.py
testData/inspection/warnUntypedFieldsDisable.py

The PR fix invalid warn on no public attribute with  `WarnUntypedFields` option
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/94

fix invalid warn on no public attribute

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/mock/stub/typing/__init__.py
testData/typecheckerinspection/field.py
testSrc/com/koxudaxi/pydantic/PydanticTypeCheckerInspectionTest.kt

This PR fixes an invalid warning when a field type is any.

Fix invalid warning when field type is any

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
testData/typecheckerinspection/class.py
testSrc/com/koxudaxi/pydantic/PydanticTypeCheckerInspectionTest.kt

This PR fixes a broken type checker. 
The type checker runs for only Pydantic models. 
I'm sorry.

fix type checker

---

README.md
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticConfigService.kt
src/com/koxudaxi/pydantic/PydanticInitializer.kt
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
testData/typecheckerinspection/acceptableType.py
testData/typecheckerinspection/acceptableTypeDisable.py
testData/typecheckerinspection/acceptableTypeInvalid.py
testData/typecheckerinspection/acceptableTypeWarning.py
testData/typecheckerinspection/parsableTypeDisable.py
testSrc/com/koxudaxi/pydantic/PydanticTypeCheckerInspectionTest.kt

This PR supports acceptable type.

support acceptable type

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticInitializer.kt
testData/initializer/pyprojecttoml/pyproject.toml
testData/mock/pydanticv1/__init__.py
testData/mock/pydanticv1/networks.py
testSrc/com/koxudaxi/pydantic/PydanticInitializerTest.kt

This PR fixes the type-map edge case.
we expect  `HttpUrl` is `pydantic.HttpUrl`.
```toml
"pydantic.HttpUrl" = ["str"]
```
But, actual path is `pydantic.networks.HttpUrl`.
This PR fixes this case.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/99

Fix type-map edge case for parsable-type and acceptable-type

---

LICENSE_apache_version_2.txt
build.gradle
docs/development.md
resources/META-INF/plugin.xml
testData/completion/classInitMethod.py
testSrc/com/jetbrains/python/PythonMockSdk.java
testSrc/com/jetbrains/python/PythonTestUtil.java
testSrc/com/jetbrains/python/fixtures/PyLightProjectDescriptor.java
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionV0Test.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

This PR adds an sdk for the unittest.
The class is copied to `testSrc/com/jetbrains` from [IntelliJ IDEA Community Edition](https://github.com/JetBrains/intellij-community)

add sdk mock for python

---

README.md
docs/index.md
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticDynamicModel.kt
src/com/koxudaxi/pydantic/PydanticDynamicModelClassType.kt
src/com/koxudaxi/pydantic/PydanticDynamicModelMemberProvider.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/mock/pydanticv1/__init__.py
testData/mock/pydanticv1/main.py
testData/mock/stub/typing/__init__.py

This PR supports a dynamic model which is created with `create_model()`
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/169

support dynamic model

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/fieldIgnore.py
testData/mock/stub/typing/__init__.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

This PR supports `ClassVar`
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/187

Support ClassVar

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
testData/ignoreinspection/validatorFullPath.py
testData/inspection/rootValidatorSelf.py
testSrc/com/koxudaxi/pydantic/PydanticIgnoreInspectionTest.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/195

Fix detecting validators decorated methods

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticDataclassTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt
src/com/koxudaxi/pydantic/PydanticFieldSearchExecutor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completionv18/genericField.py
testData/completionv18/genericKeywordArgument.py
testData/mock/pydanticv18/generics.py
testData/typeinspectionv18/genericModel.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionV18Test.kt
testSrc/com/koxudaxi/pydantic/PydanticTypeInspectionV18Test.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/275

Support GenericModel

---

requirements.txt
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt

Hello. In PyCharm 2021.2.1 there will be a breaking change in API: `com.jetbrains.python.psi.types.PyTypedDictType.Companion.match(PyTypedDictType, PyDictLiteralExpression, TypeEvalContext)` method will be removed.
The type inference for collections was refactored to fix https://youtrack.jetbrains.com/issue/PY-48799, and starting from 2021.2.1 for dict literals containing only string keys we will infer PyTypedDictType, so there'll be no need to match dict literals with TypedDicts. There's a new method for comparing the inferred TypedDicts with the type hints: `com.jetbrains.python.psi.types.PyTypedDictType.Companion.match(PyType, PyTypedDictType, TypeEvalContext)`.
PyCharm 2021.2.1 will be released near the end of August.

PyCharm 2021.2.1 API changes

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticConfigService.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/345
https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/350

Support PyCharm 2021.2

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
testData/typecheckerinspection/acceptableType.py

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/360

Fix NullPointerException in PydanticTypeCheckerInspection.kt

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/extra.py

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/367

Fix false positive detection of "extra fields not permitted"

---

build.gradle
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt

Changed signature of com.jetbrains.python.psi.types.PyLiteralType.Companion#promoteToLiteral

PyCharm API changes

---

.github/workflows/CI.yml
build.gradle
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticCacheService.kt
src/com/koxudaxi/pydantic/PydanticConfigService.kt
src/com/koxudaxi/pydantic/PydanticInitializer.kt
src/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFix.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/387

Support PyCharm 2021.3

---

.github/workflows/release.yml

The IntelliJ template assumes that the default branch will be "main", this repository uses "master".
https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/436#issuecomment-1047932399
https://github.com/koxudaxi/pydantic-pycharm-plugin/runs/5290676713?check_suite_focus=true

Fix issue where changelog PRs were failing to generate

---

CHANGELOG.md

Current pull request contains patched `CHANGELOG.md` file for the `v0.3.11` version.
Manually creating this PR due to the failed workflow: https://github.com/koxudaxi/pydantic-pycharm-plugin/runs/5290676713?check_suite_focus=true

Changelog update - v0.3.11

---

CHANGELOG.md
gradle.properties
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/mock/stub/sqlmodel/__init__.py
testData/mock/stub/sqlmodel/main.py
testData/typeinspectionv18/sqlModel.py
testSrc/com/koxudaxi/pydantic/PydanticTypeInspectionV18Test.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/418

Support SQLModel

---

.github/workflows/build.yml
CHANGELOG.md
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/com/koxudaxi/pydantic/PydanticConfigPanel.kt
src/com/koxudaxi/pydantic/PydanticConfigurable.kt
testData/typeinspectionv18/genericModel.py
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/492
https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/494
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/516
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/511

Support 2022.2

---

src/com/koxudaxi/pydantic/PydanticParametersProvider.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/569

Fix NotFound getDataclassParameters error

---

src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
testData/completionv18/insertedArgument.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionV18Test.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/580

Fix completion adds superfluous equal to field_name

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeIgnoreInspectionSuppressor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/typeinspection/fieldUnionOperatorInvalid.py
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt
testSrc/com/koxudaxi/pydantic/PydanticTypeInspectionTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/522

Support Union operator

---

src/com/koxudaxi/pydantic/PydanticDataclassTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/dataclassKeywordArgument.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/552

Improve dataclass default Value detection

---

src/com/koxudaxi/pydantic/PydanticDataclassTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/annotated.py
testData/inspectionv18/defaultFactory.py
testData/mock/pydanticv18/fields.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionV18Test.kt

Closes https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/535

Add inspection for default factory

---

README.md
docs/index.md
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticAnnotator.kt
src/com/koxudaxi/pydantic/PydanticDataclassTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFix.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/insertargumentsquickfix/dataclass.py
testData/insertargumentsquickfix/dataclass_after.py
testData/insertargumentsquickfix/lastChar.py
testData/insertargumentsquickfix/lastChar_after.py
testSrc/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFixTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/503
- Bug fix for https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/503
- Support insert arguments quick fix for `pydantic.dataclasses.dataclass`

Improve insert arguments

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/typeinspection/fieldField.py

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/475

Fix None default value on Field function

---

src/com/koxudaxi/pydantic/PydanticIgnoreInspection.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/ignoreinspection/validatorDataclass.py
testData/inspection/annotated.py
testSrc/com/koxudaxi/pydantic/PydanticIgnoreInspectionTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/466

Improve dataclass support

---

CHANGELOG.md
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticAnnotator.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/acceptsOnlyKeywordArguments.py
testData/inspection/extra.py
testData/inspection/ormMode.py

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/651

Fix wrong inspections when a model has a __call__ method

---

CHANGELOG.md
src/com/koxudaxi/pydantic/PydanticDataclassTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

This PR resolves errors of unexpected when resolving reference.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/504
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/380
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/353
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/351
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/326
https://github.com/JetBrains/intellij-community/commit/7aef8300b44e18a85aacd80f35bccebe69dd442f

Reduce unnecessary resolve in type providers

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/callTypeWithSelf.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/668

Fix wrong accepts only keyword arguments error

---

src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt
src/com/koxudaxi/pydantic/PydanticFieldSearchExecutor.kt
testData/refactor/renameMethodLocalVariable.py
testData/refactor/renameMethodLocalVariable_after.py
testData/search/methodLocalVariable.py
testSrc/com/koxudaxi/pydantic/PydanticRefactorTest.kt
testSrc/com/koxudaxi/pydantic/PydanticSearchTest.kt

Closes:  https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/484

Fix wrong renaming of a local variable name is same as field name

---

src/com/koxudaxi/pydantic/PydanticFieldSearchExecutor.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/233

Fix wrong highlighting

---

.github/workflows/build.yml
gradle.properties
src/com/koxudaxi/pydantic/PydanticInitializer.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionV0Test.kt
testSrc/com/koxudaxi/pydantic/PydanticInitializerTest.kt
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticInspectionV2Test.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt
testSrc/com/koxudaxi/pydantic/PydanticTypeCheckerInspectionTest.kt

Closese:https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/713

support 232 EAP

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCacheService.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticIgnoreInspection.kt
src/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFix.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler.kt
testData/inspectionv2/validatorSelf.py
testData/mock/pydanticv2/__init__.py
testData/mock/pydanticv2/functional_validators.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionV2Test.kt
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

Related Issues:https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/694

Support pydantic v2 validators for 232

---

src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspectionv2/validators.py
testData/mock/pydanticv2/__init__.py
testData/mock/pydanticv2/deprecated/__init__.py
testData/mock/pydanticv2/deprecated/class_validators.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionV2Test.kt

Related Issues: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/694

add migration guide url

---

src/com/koxudaxi/pydantic/PydanticDocumentationLinkProvider.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/773 https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/742

Fix NullPointerException of getExternalDocumentationUrl

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticIgnoreInspection.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler.kt
testData/ignoreinspection/validatorModeAfter.py
testData/inspectionv2/validatorField.py
testData/inspectionv2/validatorSelf.py
testSrc/com/koxudaxi/pydantic/PydanticIgnoreInspectionTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/774

treat model validator as an instance method when mode='after'

---

docs/ignore-init-arguments.md
docs/ignore-init-keyword-arguments.md
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticConfigService.kt
src/com/koxudaxi/pydantic/PydanticInitializer.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/keywordArgumentInitArgsKwargs.py
testData/completion/keywordArgumentInitArgsKwargsDisable.py
testData/completion/keywordArgumentInitKwargs.py
testData/completion/keywordArgumentInitPosition.py
testData/initializer/pyprojecttoml/pyproject.toml
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticInitializerTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/471 https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/796
Often, Third party libraries override BaseModel's `__init__` with `**kwargs`. So, the PyCharm will no longer perform completion and type checking.
Setting `ignore-init-method-arguments = true` causes init method to be ignored, but for convenience, add a new `ignore-init-method-keyword-arguments ` and enable it by default

Ignore `__init__` method if parameter is only only `**kwargs` arguments.

---

src/com/koxudaxi/pydantic/PydanticReferenceContributor.kt
testData/inspectionv18/validatorField.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionV18Test.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/784

Fix False positive for non-decorator use of validator

---

CHANGELOG.md
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/fieldAnnotated.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

Fixes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/731

Improve annotated default detection

---

CHANGELOG.md
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completionv2/fieldAnnotated.py
testData/inspectionv2/annotated.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionV2Test.kt
testSrc/com/koxudaxi/pydantic/PydanticInspectionV2Test.kt

Related PR: https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/856

Improve annotated default detection for v2

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/typeinspectionv18/genericModel.py
testSrc/com/jetbrains/python/PythonMockSdk.kt
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/876

Support 241 EAP

---

CHANGELOG.md
gradle.properties
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/inspection/readOnlyProperty.py
testData/inspectionv18/readOnlyProperty.py
testData/inspectionv18/readOnlyPropertyFrozen.py
testData/inspectionv2/modelAttribute.py
testData/inspectionv2/readOnlyPropertyFrozenConfig.py
testData/inspectionv2/readOnlyPropertyFrozenConfigDict.py

Fixes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/899

Fix unresolved ClassVar attribute error
