resources/META-INF/plugin.xml
src/org/pydantic/PydanticTypeProvider.kt

support optional without a default value

support optional without a default value

---

resources/META-INF/plugin.xml
src/org/pydantic/PydanticTypeProvider.kt

support union include None

---

README.md

The PR change the download link of the plugin which is built by travis-ci from kotlin source code.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/8

change plugin download link

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

The PR fixes a bug.
if I call a class method with a positional argument, then the plugin show error.
The plugin detects the class method as `__init__`.

 Fix class method

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt

The PR supports refactoring field names. 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/16

support refactor field names

---

resources/META-INF/plugin.xml

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/25

add description

---

src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

support Schema on field values
- Schema(...)
- Schema('abc')
- Schema(default=...)
- Schema(default='abc')
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/30

Support Schema on field values

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticIgnoreInspection.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt

The PR support to ignore waring of `self` with `@validator`
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/41

ignore self waring with @validator

---

src/com/koxudaxi/pydantic/Pydantic.kt

The PR fixes the invalid inspection on namedtuple.
#80

Fix inspection on namedtuple

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/keywordArgumentAllowPopulationByFieldName.py
testData/completion/keywordArgumentAllowPopulationByFieldNameChild.py
testData/completion/keywordArgumentAllowPopulationByFieldNameFalse.py
testData/completion/keywordArgumentAllowPopulationByFieldNameMultipleInheritance.py
testData/completion/keywordArgumentAllowPopulationByFieldNameParent.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

The PR supports allow_population_by_field_name
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/78

support allow_population_by_field_name

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/dataclassKeywordArgument.py
testData/mock/stub/dataclasses.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

This PR fixes type-provider for dataclass.
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/113

Fix type provider for dataclass

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
testData/typecheckerinspection/parsableTypeCollection.py
testSrc/com/koxudaxi/pydantic/PydanticTypeCheckerInspectionTest.kt

This PR supports a collection on parsable-type and acceptable-type
Exp
List[str] -> List[int]
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/99

support a collection on parsable-type and acceptable-type

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticInitializer.kt

This PR fixes types of methods and functions.
The plugin copy py files into stub dir as stubs files (a.k.a *.pyi).
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/122

Fix types of methods and functions

---

README.md
docs/index.md
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticAnnotator.kt
src/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFix.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/insertargumentsquickfix/dataclass.py
testData/insertargumentsquickfix/dataclass_after.py
testData/insertargumentsquickfix/lastChar.py
testData/insertargumentsquickfix/lastCharOnlyRequired.py
testData/insertargumentsquickfix/lastCharOnlyRequired_after.py
testData/insertargumentsquickfix/lastChar_after.py
testData/insertargumentsquickfix/noArguments.py
testData/insertargumentsquickfix/noArgumentsOnlyRequired.py
testData/insertargumentsquickfix/noArgumentsOnlyRequired_after.py
testData/insertargumentsquickfix/noArguments_after.py
testData/insertargumentsquickfix/partArguments.py
testData/insertargumentsquickfix/partArgumentsOnlyRequired.py
testData/insertargumentsquickfix/partArgumentsOnlyRequired_after.py
testData/insertargumentsquickfix/partArguments_after.py
testData/inspection/acceptsOnlyKeywordArguments.py
testData/inspection/acceptsOnlyKeywordArgumentsSingleStarArgument.py
testData/typecheckerinspection/field.py
testSrc/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFixTest.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/139

support inserting arguments

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/168

Remove deletion error

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticConfigService.kt
src/com/koxudaxi/pydantic/PydanticInitializer.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/201

Fix config service error

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt

This PR fixes inserting arguments when the model is referenced object.

Fix inserting arguments

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/fieldIgnore.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/214

Support keep untouched

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completion/fieldCustomRoot.py
testData/completion/keywordArgumentCustomRoot.py
testData/inspection/customRoot.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/226

Support custom root field

---

src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/248

Fix DisposalException

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/mock/stub/typing/__init__.py
testData/typecheckerinspection/fieldImportTyping.py
testData/typecheckerinspection/fieldImportTypingInvalid.py
testSrc/com/koxudaxi/pydantic/PydanticTypeCheckerInspectionTest.kt

- https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/257

Support `import typing`

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticAnnotator.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/mock/pydanticv18/env_settings.py
testData/typeinspectionv18/baseSetting.py
testSrc/com/koxudaxi/pydantic/PydanticTypeInspectionV18Test.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/274

Support extra init args on baseSetting

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/configDuplicate.py
testData/inspection/kwargConfig.py
testData/inspectionv18/configDuplicate.py
testData/inspectionv18/kwargConfig.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticInspectionV18Test.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/284

Support config parameters on class kwargs

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCacheService.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/inspectionv18/configDuplicate.py
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/296

Fix wrong an error for a duplicate in config.

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completionv18/overrideInitField.py
testData/completionv18/overrideInitKeywordArgument.py
testData/typeinspectionv18/overrideInit.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionV18Test.kt
testSrc/com/koxudaxi/pydantic/PydanticTypeInspectionV18Test.kt

- https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/295

Fix wrong call parameters when init is defined

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticAnnotator.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/inspection/acceptsOnlyKeywordArgumentsInit.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticTypeInspectionV18Test.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/295

Fix wrong call parameter with **kwargs

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/completionv18/aliasNameKeywordArgument.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionV18Test.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/300

Ignore invalid alias name

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/typeinspection/fieldField.py
testData/typeinspection/fieldFieldInvalid.py

- https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/318

Fix default value by variable for Field is not recognized

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspection/extra.py
testData/mock/pydanticv1/__init__.py
testData/mock/pydanticv1/main.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionTest.kt

- add unittest
- https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/319

Support error for extra attribute with extra = 'forbid' option

---

build.gradle

https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/350

Fix untilBuild 212.*

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticAnnotator.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/265

Fix Outdated Stub in index error on PydanticAnnotator.kt

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticDataclassTypeProvider.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/326
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/291

Fix PydanticDataclassTypeProvider.kt error

---

build.gradle
resources/META-INF/plugin.xml

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/404

Support IntelliJ IDEA 2021.3

---

docs/mypy-compatible.md
resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticConfigPanel.form

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/406

Fix a typo in the settings

---

resources/META-INF/plugin.xml
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/392

Fix Null Pointer Exception in PydanticTypeCheckerInspection

---

build.gradle

Reverts koxudaxi/pydantic-pycharm-plugin#438

Revert "Bump org.jetbrains.intellij from 1.3.1 to 1.4.0"

---

src/com/koxudaxi/pydantic/PydanticInitializer.kt

https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/525

Fix unexpected errors when deleting project

---

.github/workflows/build.yml
build.gradle.kts

kotlinx-kover is better for kotlin than jacoco and is the recommended coverage tool for Intellij plugins

Switch from jacoco to kotlinx-Kover

---

src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt

closes:https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/538

avoid AlreadyDisposedException

---

CHANGELOG.md
build.gradle.kts
gradle.properties
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/632

Support 2023.1 EAP

---

build.gradle.kts
gradle.properties

https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#incremental-compilation
kotlin.incremental.useClasspathSnapshot=false

Support Kotlin 1.8.20 

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCacheService.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticIgnoreInspection.kt
src/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFix.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler.kt
testData/inspectionv2/validatorSelf.py
testData/mock/pydanticv2/__init__.py
testData/mock/pydanticv2/functional_validators.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionV2Test.kt
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

Related Issues:https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/694

Support pydantic v2 validators

---

src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCacheService.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticIgnoreInspection.kt
src/com/koxudaxi/pydantic/PydanticInsertArgumentsQuickFix.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
src/com/koxudaxi/pydantic/PydanticPackageManagerListener.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
src/com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler.kt
testData/inspectionv2/validatorSelf.py
testData/mock/pydanticv2/__init__.py
testData/mock/pydanticv2/functional_validators.py
testSrc/com/koxudaxi/pydantic/PydanticInspectionV2Test.kt
testSrc/com/koxudaxi/pydantic/PydanticPackageManagerListenerTest.kt
testSrc/com/koxudaxi/pydantic/PydanticTestCase.kt

Related Issues:https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/694

Support pydantic v2 validators for 231

---

src/com/koxudaxi/pydantic/PydanticDocumentationLinkProvider.kt

Related Issues: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/694

Update v2 external document url for 232

---

README.md
docs/index.md
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
testData/completionv18/validatorField.py
testData/completionv2/validatorField.py
testData/mock/pydanticv2/__init__.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionV18Test.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionV2Test.kt

Add validator field argument completion

---

src/com/koxudaxi/pydantic/PydanticCompletionContributor.kt
src/com/koxudaxi/pydantic/PydanticInspection.kt
testData/inspectionv2/validatorField.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionV18Test.kt
testSrc/com/koxudaxi/pydantic/PydanticCompletionV2Test.kt

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/775

Fix false positive validator asterisk

---

CHANGELOG.md
gradle.properties
testData/typeinspection/dynamicModel.py
testData/typeinspectionv18/dataclass.py
testData/typeinspectionv18/dynamicModel.py
testData/typeinspectionv18/genericModel.py
testData/typeinspectionv18/sqlModel.py

Closes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/809

Support 2023.3 EAP

---

.github/workflows/build.yml
CHANGELOG.md
build.gradle.kts
gradle.properties
src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt
testData/typeinspection/dynamicModel.py
testData/typeinspectionv18/dataclass.py
testData/typeinspectionv18/dynamicModel.py
testData/typeinspectionv18/genericModel.py
testData/typeinspectionv18/sqlModel.py
testSrc/com/koxudaxi/pydantic/PydanticCompletionTest.kt

Fixes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/839

Support PyCharm 2023.3

---

CHANGELOG.md
gradle.properties
src/com/koxudaxi/pydantic/Pydantic.kt
src/com/koxudaxi/pydantic/PydanticTypeProvider.kt

Fixes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/691

Fix named argument as positional in popup

---

.github/workflows/build.yml
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts

And pull changes from the plugin template

(🎁) Update versions

---

.github/workflows/build.yml
CHANGELOG.md
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts

Related Issues: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/961

Support 242 EAP

---

CHANGELOG.md
gradle.properties
src/com/koxudaxi/pydantic/Pydantic.kt

Fixes: https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/974

Resolve plugin crash in PyCharm Community Edition after 2024.2 update
